version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: sales-weather-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sales_weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: sales-weather-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - ./backend/api/.env
    volumes:
      - ./backend/api/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: sales-weather-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
volumes:
  postgres_data: